### ISSUE TITLE
Delphi 10.4 - Ajuste no método "UpdateById"

### ISSUE THREAD

**Issue by jmjardim05** [HashLoad/ragna#10]
A função UpdateById() chama EditFromJson() que por sua vez chama o helper LoadFromJson()

LoadFromJson() insere um novo registro na base, logo sempre envia um comando INSERT.

Para enviar um UPDATE, precisa chamar o helper MergeFromJsonObject().

Segue solução sugerida:

```Pascal
procedure TRagna.UpdateById(const AField: TField; const AValue: Int64; const ABody: TJSONObject);
begin
  FQuery.FindById(AField, AValue).OpenUp.MergeFromJSONObject(ABody, False);
end;
```

**Comment by viniciussanchez** [comment]
Obrigado.... você não quer enviar um pull request ajustando o código?
