### ISSUE TITLE
Like implementation

### ISSUE THREAD

**Issue by jsisolucoes** [HashLoad/ragna#12]
Olá,

Eu corrigi um erro no Ragna.Criteria.Impl na procedure "Like", ela não estava formatando corretamente a PHRASE.
Aproveitei e coloquei uma verificação do sinal percentual (%) usado no like.

Eu não consegui fazer um pull request, então vou enviar o arquivo alterado aqui.

Outra coisa que observei é que a procedure Order possui overload para string mas nao possui a implementação.
Esse código eu não criei, mas se for o caso eu crio a implementação do overload.

[Ragna.Criteria.Impl.pas.zip](https://github.com/HashLoad/ragna/files/8484839/Ragna.Criteria.Impl.pas.zip)

**Comment by viniciussanchez** [comment]
Obrigado
