### ISSUE TITLE
Erro no Where

### ISSUE THREAD

**Issue by phdorocha** [HashLoad/ragna#6]
Ao tentar realizar consultas usando o banco de dados FB me retorna o seguinte erro:
Internal Application Error
'' is not a valid integer value for Integer type

Criei um banco no FB para testar o Kanbana e me retorna o mesmo erro com o banco FB.
Usei o Tokyo + Windows 10 + Projeto Console + FB 2.5

**Comment by viniciussanchez** [comment]
@phdorocha adicione o SQL aqui fazendo favor, e se possível o script que usou pra criar o banco

**Comment by phdorocha** [comment]
[create_database_base.txt](https://github.com/HashLoad/ragna/files/4746829/create_database_base.txt)
O SQL que usei foi o *select * from bots*.
Daí usei o ragna com: 
  NFes.NFe
        .Where(NFeID.ToString)
        .Equals(NFeId)
        .OpenUp

**Comment by phdorocha** [comment]
Na verdade isso que postei no Ragna é de outro projeto, porque o do BOT eu já alterei aqui mas fiz dessa mesma forma aí. Como a conversão para JSON estava retornando erro, eu converto usando um método que o Ivan fez pra mim.

**Comment by viniciussanchez** [comment]
> Internal Application Error
'' is not a valid integer value for Integer type

Acontece porque você não deve ter definido as variáveis de ambiente necessárias para o projeto do Kanbana-API funcionar.
