### ISSUE TITLE
Devart UniDAC support

### ISSUE THREAD

**Issue by ertankucukoglu** [HashLoad/ragna#8]
Hello,

I have completed modifications on my side. However, I am not good at using git. I failed to add a new pull request.

Attached is exported ZIP file of my commit in my copy of the repository. This is the best that I could come up with.

Hope it can be used and is accepted to be merged in original codes.

Thanks & Regards,
Ertan

[3c5e31722388af232ca348770c6ae9e11a16de6c.zip](https://github.com/HashLoad/ragna/files/5766648/3c5e31722388af232ca348770c6ae9e11a16de6c.zip)

**Comment by viniciussanchez** [comment]
Thank you very much. Let's check and add to the project.

**Comment by ertankucukoglu** [comment]
BTW, I forgot and left ragna.inc file set as defined UNIDAC. You will probably want to set it to FIREDAC as that is default and is the way peopled used to use ragna.

UniDAC users can always modify ragna.inc file and set it to use UniDAC instead.

**Comment by viniciussanchez** [comment]
@ertankucukoglu thanks for the contribution. I used compilation directives. I didn't use the .inc file
