### ISSUE TITLE
Memory Leaks

### ISSUE THREAD

**Issue by Pedro-Guilherme** [HashLoad/ragna#9]
Estou usando o exemplo do KanbanaApi para aprender sobre o Ragna, porem estou tendo memory leaks ao usar o ragna em qualquer operação...
Não sei se precisa de alguma configuração específica no projeto, mas estou meio perdido

Segue o código que gera os memory leaks no meu projeto
`qryUsuarios.Where('email').Equals(vEmail).&And('senha').Equals(vSenha).OpenUp;`

Se alguem tiver alguma idéia sobre o que pode estar acontecendo, já agradeço a ajuda

**Comment by viniciussanchez** [comment]
Resolveu o problema?
